workflows:
  ios-native-build:
    name: Median iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 15

    scripts:
      - name: Install CocoaPods
        script: |
          pod repo remove gonative || true
          pod repo add gonative https://github.com/gonativeio/gonative-ios-specs.git || true
          pod install --verbose

      - name: Archive App
        script: |
          xcodebuild archive \
            -workspace "StockManagement.xcworkspace" \
            -scheme "StockManagement" \
            -configuration Release \
            -archivePath build/StockManagement.xcarchive \
            CODE_SIGNING_ALLOWED=NO

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/StockManagement.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build

    artifacts:
      - build/*.ipa
